# 1. Intro

In [1]:
import torch

In [3]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [5]:
a[1]

torch.Tensor

In [7]:
a[2] = 2
a

tensor([1., 1., 2.])

In [8]:
points = torch.zeros(6)
points

tensor([0., 0., 0., 0., 0., 0.])

In [9]:
for i in range(len(points)):
    points[i] += i
points

tensor([0., 1., 2., 3., 4., 5.])

In [12]:
points = torch.tensor([ [4.0, 1.0],
                        [5.0, 3.0],
                        [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [15]:
print(points.shape)

points2 = torch.zeros(points.shape)
points2

torch.Size([3, 2])


tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [23]:
for i in range(len(points2)):
    for j in range(len(points2[0])):
        points2[i, j] = i + j
points2

tensor([[0., 1.],
        [1., 2.],
        [2., 3.]])

In [24]:
points2[0,1]

tensor(1.)

# 2. Tensor Indexing