In [ ]:
import numpy as np

# 4-1

In [ ]:
arr1 = np.random.randint(100, size=10)

print(arr1)
print(np.sort(arr1))
print(arr1)

arr1.sort()
print(arr1)
print(arr1[::-1])

# 4-2

In [14]:
arr2 = np.random.randint(20, size=(3,4))

print(arr2, "\n")
print(np.sort(arr2, axis=0)[::-1], "\n")

[[ 6 15 18 16]
 [ 4 13 12 14]
 [ 8  7 17 14]] 

[[ 8 15 18 16]
 [ 6 13 17 14]
 [ 4  7 12 14]] 


In [15]:
print(np.sort(arr2, axis=0), "\n")
print(np.argsort(arr2, axis=0), "\n")
print(np.sort(arr2, axis=1), "\n")
print(np.argsort(arr2, axis=1), "\n")

[[ 4  7 12 14]
 [ 6 13 17 14]
 [ 8 15 18 16]] 

[[1 2 1 1]
 [0 1 2 2]
 [2 0 0 0]] 

[[ 6 15 16 18]
 [ 4 12 13 14]
 [ 7  8 14 17]] 

[[0 1 3 2]
 [0 2 1 3]
 [1 0 3 2]] 
