In [ ]:
import numpy as np

# 2-1

In [ ]:
arr1 = np.arange(0,15).reshape(3,5)
print(arr1)

In [ ]:
print(arr1[0][2])

In [ ]:
print(arr1[:, 1:4])

In [ ]:
arr2 = np.arange(0,25).reshape(5,5)
print(arr2)

In [ ]:
print(arr2[2:,1:-1])

# 2-2

In [ ]:
arr1 = np.arange(26)
filtered_arr1 = arr1[arr1 % 5 == 0]

print(filtered_arr1)
print(filtered_arr1[[1,3,5]])

In [ ]:
arr2 = np.arange(60)
filtered_arr2 = arr2[arr2 % 5 ==0].reshape(3,4)
print(filtered_arr2)

In [ ]:
print(filtered_arr2[0:, [0,3]])

# 2-3

In [ ]:
print(filtered_arr1[[True, False, True, True, False, True]])

In [ ]:
print(filtered_arr2[[True,False,True],[False,False,False,True]])

In [34]:
arr = np.array([[1,2,3,4],
                [5,6,7,8]])
print(arr)
print(arr > 2)
print(arr[arr > 2])

[[1 2 3 4]
 [5 6 7 8]]
[[False False  True  True]
 [ True  True  True  True]]
[3 4 5 6 7 8]
